# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'default_option.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_defaultOption(object):
    def setupUi(self, defaultOption):
        defaultOption.setObjectName("defaultOption")
        defaultOption.resize(268, 317)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/logo-black"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        defaultOption.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(defaultOption)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.teamThreshold = QtWidgets.QDoubleSpinBox(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teamThreshold.sizePolicy().hasHeightForWidth())
        self.teamThreshold.setSizePolicy(sizePolicy)
        self.teamThreshold.setDecimals(1)
        self.teamThreshold.setSingleStep(0.5)
        self.teamThreshold.setObjectName("teamThreshold")
        self.gridLayout.addWidget(self.teamThreshold, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.weakSupport = QtWidgets.QDoubleSpinBox(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weakSupport.sizePolicy().hasHeightForWidth())
        self.weakSupport.setSizePolicy(sizePolicy)
        self.weakSupport.setDecimals(1)
        self.weakSupport.setSingleStep(0.5)
        self.weakSupport.setObjectName("weakSupport")
        self.gridLayout.addWidget(self.weakSupport, 1, 1, 1, 1)
        self.weakOppose = QtWidgets.QDoubleSpinBox(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weakOppose.sizePolicy().hasHeightForWidth())
        self.weakOppose.setSizePolicy(sizePolicy)
        self.weakOppose.setDecimals(1)
        self.weakOppose.setMinimum(-100.0)
        self.weakOppose.setMaximum(0.0)
        self.weakOppose.setSingleStep(0.5)
        self.weakOppose.setObjectName("weakOppose")
        self.gridLayout.addWidget(self.weakOppose, 3, 1, 1, 1)
        self.strongSupport = QtWidgets.QDoubleSpinBox(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strongSupport.sizePolicy().hasHeightForWidth())
        self.strongSupport.setSizePolicy(sizePolicy)
        self.strongSupport.setDecimals(1)
        self.strongSupport.setSingleStep(0.5)
        self.strongSupport.setObjectName("strongSupport")
        self.gridLayout.addWidget(self.strongSupport, 2, 1, 1, 1)
        self.strongOppose = QtWidgets.QDoubleSpinBox(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strongOppose.sizePolicy().hasHeightForWidth())
        self.strongOppose.setSizePolicy(sizePolicy)
        self.strongOppose.setDecimals(1)
        self.strongOppose.setMinimum(-100.0)
        self.strongOppose.setMaximum(0.0)
        self.strongOppose.setSingleStep(0.5)
        self.strongOppose.setObjectName("strongOppose")
        self.gridLayout.addWidget(self.strongOppose, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.voteRange = QtWidgets.QDoubleSpinBox(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voteRange.sizePolicy().hasHeightForWidth())
        self.voteRange.setSizePolicy(sizePolicy)
        self.voteRange.setDecimals(1)
        self.voteRange.setSingleStep(0.5)
        self.voteRange.setObjectName("voteRange")
        self.gridLayout.addWidget(self.voteRange, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(defaultOption)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.rate = QtWidgets.QDoubleSpinBox(defaultOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate.sizePolicy().hasHeightForWidth())
        self.rate.setSizePolicy(sizePolicy)
        self.rate.setDecimals(2)
        self.rate.setMaximum(1.0)
        self.rate.setSingleStep(0.05)
        self.rate.setObjectName("rate")
        self.gridLayout.addWidget(self.rate, 6, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(defaultOption)
        QtCore.QMetaObject.connectSlotsByName(defaultOption)

    def retranslateUi(self, defaultOption):
        _translate = QtCore.QCoreApplication.translate
        defaultOption.setWindowTitle(_translate("defaultOption", "默认设置"))
        self.label_4.setText(_translate("defaultOption", "轻踩幅度："))
        self.label_5.setText(_translate("defaultOption", "重踩幅度："))
        self.label_2.setText(_translate("defaultOption", "暗捞幅度："))
        self.label.setText(_translate("defaultOption", "团队阈值："))
        self.label_3.setText(_translate("defaultOption", "明捞幅度："))
        self.label_6.setText(_translate("defaultOption", "投票幅度："))
        self.label_7.setText(_translate("defaultOption", "团队概率初始值："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    defaultOption = QtWidgets.QDialog()
    ui = Ui_defaultOption()
    ui.setupUi(defaultOption)
    defaultOption.show()
    sys.exit(app.exec_())

